@endpoint = https://v1brla82hd.execute-api.eu-west-1.amazonaws.com/prod

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces/
###

PUT {{endpoint}}/spaces?spaceId=e16b2c37-077f-4f93-9c88-2d4a248be71d
Content-Type: application/json

{
    "location": "Updated Location"
}
###

GET {{endpoint}}/spaces?location=London
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Londonzzz",
    "name": "Best locationzzz"
}
###