@endpoint = https://v1brla82hd.execute-api.eu-west-1.amazonaws.com/prod
@token = eyJraWQiOiJoMVhhT1JtSjV5NXM0ZzFzd1NndkV6dmNST2ZlamdyQzhnNTFJWllOdDNVPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjZDVmNjZhYi00YTJjLTRjZDUtYjg4NS01N2I0ZTU0ZTZjYTMiLCJhdWQiOiIyZjhibWFsYnBhZW5ndmNlNjUzYTA5Yzh2aCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJldmVudF9pZCI6IjU1YjlkM2RhLWVmNGItNDk4Yy05ODJlLWJiZThlMGQxOWUxZSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjIwODkyNjYxLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0xLmFtYXpvbmF3cy5jb21cL2V1LXdlc3QtMV9qMUN0MTUzNm0iLCJjb2duaXRvOnVzZXJuYW1lIjoiYmFyb3NhbnUiLCJleHAiOjE2MjA4OTYyNjEsImlhdCI6MTYyMDg5MjY2MSwiZW1haWwiOiJiYXJvc2FudUBnbWFpbC5jb20ifQ.Kt6aeTDvNmsW7-hxFkNYCZFUiTJ7hWVQX4zoQcpP1PL2-T2bkuuiLQgwiDb0lQsXP29uN8GdH3PO8QJrv2qiErFGXVCtBckAXQYKfFjResvMe1GHlKOaOZ2_aQ7Igesehjx41yxfzOa1a0PAmgN65APHhuKAWZqeztqx95ZOFfXRRUVgSwTM6_axDS65cRc_zFoCGPeaKFH0qnQUdiAhVHyzzroi3BKY2x5CSDYRY241ajfyYDWEUj77IZU_eUxLpV-DttUNQtRxJlGUiKqlAtOMsv_Vkl4EYy1fT4PimTQF6dFjQzR-112g58RVnxvenfzXXStXsKF4bu7DAxZsVw

GET {{endpoint}}/hello/
Authorization: {{token}}
###
GET {{endpoint}}/spaces/
###

GET {{endpoint}}/spaces?spaceId=64c87073-5ffe-4cbd-b867-2645b91fccde
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Londonzzz",
    "name": "Best locationzzz"
}
###

PUT {{endpoint}}/spaces?spaceId=64c87073-5ffe-4cbd-b867-2645b91fccde
Content-Type: application/json

{
    "location": "Updated Location"
}
###

DELETE  {{endpoint}}/spaces?spaceId=64c87073-5ffe-4cbd-b867-2645b91fccde
###

